title: Seb Beck
url: https://blog.sebbeck.com
description: Energy and Politics
theme: minima


twitter:
  username: sebexor
  card: summary
author:
  twitter: sebexor
  name: sebexor
  avatar: # Add avatar URL here or remove the line
  email: sebbeck@protonmail.com
  url: https://sebbeck.com
github: 
  username: sebanalysis
permalink: pretty
repository: sebanalysis/sidey

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
